name: masterclass_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.3.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  modular_test: ^1.0.1+1

flutter:
  uses-material-design: true
  assets:
   - assets/

